### ISSUE TITLE
Create new trial types (Chirp+Forage Reward)

### ISSUE THREAD

**Issue by rolsonjames** [low-bart/AbbasCentral#1]
Find forage reward timestamps that are super close to LaserOn Timestamps, these will be trials that they got rewarded right before the chirp. Is this why we see the weird LFP activity before the chirp? 

![Capture](https://user-images.githubusercontent.com/28582722/221729335-b5a90492-5558-49d2-8bb6-a5817a749b3d.PNG)
Chirp happens at 5000 WTF

**Comment by low-bart** [comment]
I think maybe the best way to deal with this would be to alter the trial types in the session data, adding a new type of trial for those trials where these two parameters are true, and then add a new field in your trialTypes section of config.ini. The downside of this approach is those trials will be examined separately from the original set of trials they were subsampled from.

**Comment by low-bart** [comment]
The function to adjust the trialTypes is in the BehDat class by the name add_focus_trialTypes.
