### ISSUE TITLE
Remove Noisy Data 

### ISSUE THREAD

**Issue by rolsonjames** [low-bart/AbbasCentral#10]
modify behdat methods so they can deal with noisy data removal in kilosort preprocessing step. Perhaps, a post method after running normal methods?

**Comment by low-bart** [comment]
The function remove_noisy_periods is finished, it can now be implemented in functions who output a matrix of trials by bins. The objects still need to have a field added to their info field called noisyPeriods, which is a vector of the sample points that need to be removed from the output.

**Comment by low-bart** [comment]
This is not really in use but could be implemented later if we decide we want to use it.
