### ISSUE TITLE
changes to app

### ISSUE THREAD

**Issue by MiltonRu** [low-bart/AbbasCentral#11]
- toggles for trial types enabling plotting multiple trialtypes in same plot (with indication of line color)
- option for standard error envelope for psth lines
- method to run all analyses in a batch before starting to dig into with the app, so things move quicker later
- system to save app data for everything so it doesn't all need to run if the  app gets closed

**Comment by low-bart** [comment]
Multiple trialtype/alignment combinations can now be viewed in the PSTH and raster panels of the app, with separate functionality for the top and bottom panel. PSTH plots come by default with standard error. LFP data is now saved in H5 files in your root directory, and average cwt power for all outcomes/trialtypes for a given alignment can now be calculated in bulk for all sessions and alignments and saved to this file by pushing 'Calculate All Power'. This file remains in your directory when you close the app and can be accessed in future sessions.
