### ISSUE TITLE
Trial sets

### ISSUE THREAD

**Issue by MiltonRu** [low-bart/AbbasCentral#13]
Please create a way to have a third grouping of trial sets (not trial types or outcome based). Types of sets that would be nice to have:

based on trial count (ie compare trials 1:10 vs 30:70, etc)
based on bpod event system ( ie create new psuedotrials around incorrect pokes)

![image](https://github.com/abbaslab-va/AbbasCentral/assets/139919529/0118ffec-2dd4-43af-af88-9c2d2756b397)
This would work well as a third grouping below these first two, with options to add based on trial count or bpod event criteria (including as subsets of other sets like trial type or outcome)

**Comment by low-bart** [comment]
This is now available in the app utilizing the new PresetManager class. This also greatly can simplify BehDat class method calls using the 'preset' parameter.
