### ISSUE TITLE
Adding labels

### ISSUE THREAD

**Issue by MiltonRu** [low-bart/AbbasCentral#15]
Would be nice to have better plot labels - particularly for trial type on Y axis, trial number (ie is top trial 1 or end), as well as a T_0 for rasters and psths. 

Thanks  Lowell!

**Comment by low-bart** [comment]
Labels are added for raster and psth in app. What do you mean about the trial type label?

**Comment by low-bart** [comment]
Plot labeling has been added to raster plot.
