### ISSUE TITLE
colorful population-response plot

### ISSUE THREAD

**Issue by MiltonRu** [low-bart/AbbasCentral#16]
This would also be cool to add - referring to the type of plot Alex and Randall both show

**Comment by low-bart** [comment]
The method mean_population_response is now available in the BehDat class. Still needs integration into AbbasCentral app

**Comment by low-bart** [comment]
Function is now supported in app. 

edit: I just reopened this bc I realize it needs cell support for multiple trialtypes and outcomes. Not sure how to handle that to display different conditions simultaneously with a heatmap.
