### ISSUE TITLE
General app errors

### ISSUE THREAD

**Issue by rolsonjames** [low-bart/AbbasCentral#4]
When hovering over plot in app error occurs 
"Warning: Error updating AxesToolbar."
"Invalid type of input arguments (should be uint64)"

add replot button in app

**Comment by rolsonjames** [comment]
once everthing is set once and then you change alignment.. it errors out. can fix by then selecting a neuron again

**Comment by low-bart** [comment]
Not sure the cause of these errors. I could not replicate the warnings or the error that you were given. Try pulling down the latest changes and see if they persist - I also added the replot button which should help as a temporary workaround if you still get these errors.
