### ISSUE TITLE
Find subset of bpod events

### ISSUE THREAD

**Issue by low-bart** [low-bart/AbbasCentral#7]
Also can you make it so one can align to a given timestamp relative to another in a trial.

_Originally posted by @rolsonjames in https://github.com/low-bart/AbbasCentral/issues/2#issuecomment-1454056161_
            
Adapt find_bpod_event to find events that happened at a certain point in a trial. For example, find all PortOuts that happened prior to a Reward event in a trial, or within a given window of time around the event.

**Comment by rolsonjames** [comment]
implement dandy randy's sequencing algorithm to find correct event prior to choice of state
